/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8faf8',
        background: '#f8faf8',
        'surface-dim': '#d9dad9',
        'surface-bright': '#f8faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f3',
        'surface-container': '#edeeed',
        'surface-container-high': '#e7e8e7',
        'surface-container-highest': '#e1e3e2',
        'surface-variant': '#e1e3e2',
        'surface-tint': '#2d6764',
        'on-surface': '#191c1c',
        'on-surface-variant': '#404948',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1f0',
        outline: '#707978',
        'outline-variant': '#bfc8c7',
        primary: '#00423f',
        'on-primary': '#ffffff',
        'primary-container': '#1d5a57',
        'on-primary-container': '#95cfcb',
        'primary-fixed': '#b2eee9',
        'primary-fixed-dim': '#97d1cd',
        'on-primary-fixed': '#00201e',
        'on-primary-fixed-variant': '#0d4f4c',
        'inverse-primary': '#97d1cd',
        secondary: '#3e6652',
        'on-secondary': '#ffffff',
        'secondary-container': '#c0edd3',
        'on-secondary-container': '#446d58',
        'secondary-fixed': '#c0edd3',
        'secondary-fixed-dim': '#a5d0b8',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#264e3c',
        tertiary: '#5b2f1a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#76452f',
        'on-tertiary-container': '#f9b599',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#fbb79a',
        'on-tertiary-fixed': '#341102',
        'on-tertiary-fixed-variant': '#693b25',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        accent: '#fcc419',
        'accent-dark': '#7a5a00',
        'on-accent': '#1d5a57',
        'party-blue': '#1a4188',
        'deep-forest': '#1d5a57',
        'sage-growth': '#7aa48d',
        'prestige-gold': '#fcc419',
        'off-white': '#f8faf8',
        'slate-gray': '#334155',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
        gutter: '24px',
        unit: '8px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        headline: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Libre Franklin', 'system-ui', 'sans-serif'],
        label: ['Montserrat', 'system-ui', 'sans-serif'],
        sans: ['Libre Franklin', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '1.35', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
