/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        background: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#1b5db1',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424752',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#727783',
        'outline-variant': '#c2c6d3',
        primary: '#003b7b',
        'on-primary': '#ffffff',
        'primary-container': '#0052a5',
        'on-primary-container': '#acc9ff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed': '#001b3e',
        'on-primary-fixed-variant': '#00458d',
        'inverse-primary': '#aac7ff',
        secondary: '#1b6b3a',
        'on-secondary': '#ffffff',
        'secondary-container': '#a5f4b6',
        'on-secondary-container': '#005227',
        'secondary-fixed': '#a5f4b6',
        'secondary-fixed-dim': '#8ad89c',
        'on-secondary-fixed': '#00210c',
        'on-secondary-fixed-variant': '#005227',
        tertiary: '#800005',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ac000a',
        'on-tertiary-container': '#ffb6ad',
        'tertiary-fixed': '#ffdad5',
        'tertiary-fixed-dim': '#ffb4aa',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#930007',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        accent: '#f5b800',
        'accent-dark': '#d99e00',
        'on-accent': '#1a1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '16px',
        'container-max-width': '1200px',
        gutter: '24px',
        unit: '8px',
      },
      maxWidth: {
        'container-max-width': '1200px',
      },
      fontFamily: {
        headline: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Montserrat', 'system-ui', 'sans-serif'],
        label: ['Montserrat', 'system-ui', 'sans-serif'],
        sans: ['Montserrat', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
